### ISSUE TITLE
In swudsSample, some variables, like selected permits, are boolean and all NA's.

### ISSUE THREAD

**Issue by grrmartin-USGS** [USGS-R/wateRuse_swuds#6]
Found that some variables, such as FROM_EPWS_USEPA, in the data set swudsSample are showing up as boolean rather than expected character, and all rows are NA, even though the original water quantity file contained values.

**Comment by ldecicco-USGS** [comment]
I think I got this fixed by adding `guess_max = 2000` to the `readxl::read_xlsx` function.
